### ISSUE TITLE
iamsystem_matcher n'a pas de propagation d'attribut "is_negated" "is_family"

### ISSUE THREAD

**Issue by Vitalizful** [TeamHeka/medkit#12]
Context : Dans un contexte de NER, on a utilisé l'outil iamsystem_matcher proposé par medkit afin d'annoter un document en souhaitant en parallèle appliquer une détection des negations et des antécédents familiaux.

Problème : Contrairement à ce que propose le matcher d'entité par regex (regexp_matcher = RegexpMatcher(rules=regexp_rules, attrs_to_copy=["is_negated"])) l'annotateur iamsystem_matcher ne propose pas de propagation d'attributs. Ainsi les entités reconnues n'ont pas d'attribut "is_negated" ou "is_family".

Exemple de code pour reproduire l'erreur :
"
from medkit.text.ner.iamsystem_matcher import MedkitKeyword, IAMSystemMatcher
from medkit.core.text import TextDocument
from medkit.text.context import NegationDetector, NegationDetectorRule, FamilyDetector, FamilyDetectorRule
from iamsystem import Matcher
from iamsystem import ESpellWiseAlgo
from medkit.text.segmentation import SentenceTokenizer, SyntagmaTokenizer

keywords_list=[]
keywords_list.append(MedkitKeyword(label="poumon gauche", kb_id="M001", kb_name="manual", ent_label="anatomy"))
keywords_list.append(MedkitKeyword(label="vascularite", kb_id="M002", kb_name="manual", ent_label="disorder"))

matcher = Matcher.build(
    keywords=keywords_list,
    spellwise=[dict(measure=ESpellWiseAlgo.LEVENSHTEIN, max_distance=1, min_nb_char=5)],
    stopwords=["et"],
    w=2
)
iam = IAMSystemMatcher(matcher = matcher)

neg_detector = NegationDetector(output_label="is_negated")
fam_detector = FamilyDetector(output_label="family")

doc = TextDocument(text="Le patient présente une asténie de grade 2 et une anémie de grade 3. Atteinte du poumon gauche et droit. Il est traité par chimiothérapie. Son père est décédé d'un cancer du poumon. Il n'a pas de vascularite.")

sent_tokenizer = SentenceTokenizer(
    output_label="sentence",
    punct_chars=[".", "?", "!", "\n"],
)

sentences = sent_tokenizer.run([doc.raw_segment])
neg_detector.run(sentences)
fam_detector.run(sentences)
entities = iam.run([doc.raw_segment])
for entity in entities:
    doc.anns.add(entity)

print("text=", entity.text, ", label=", entity.label, ", is_negated=", entity.attrs.get(label="is_negated"), ", spans=", entity.spans, sep='')
#print(f"text='{entity.text}', label={entity.label}, is_negated={entity.attrs.get(label="is_negated")[0].value}, spans={entity.spans}")
#print(f"text='{entity.text}', label={entity.label}, spans={entity.spans}")
"

**Comment by khuynh11** [comment]
Integrated in https://github.com/TeamHeka/medkit/releases/tag/0.6.0
Tutorial example in https://medkit.readthedocs.io/en/0.6.0/examples/iamsystem.html
